apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-app
  name: frontend-deployment
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: my-app
    spec:
      # --- 1. POD-LEVEL SECURITY ---
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: frontend
          image: everyday-is-devops-day-frontend:sha-a123
          imagePullPolicy: IfNotPresent

          # --- 2. CONTAINER-LEVEL SECURITY ---
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secrets

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2

          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1

          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
