apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-dev
namePrefix: dev-

resources:
  - ../../base/frontend # Ensure this points directly to where base kustomization.yaml is
  - ../../base/backend
  - ../../base/shared
  - namespace.yaml
  - ingress.yaml

# Only inject labels UNIQUE to the 'dev' environment:
labels:
  - pairs:
      app.kubernetes.io/instance: frontend-dev
      environment: dev
    includeTemplates: true
