# =============================================================================
# Development Environment
# Node 22.14.0-alpine pinned to the same version as production
# =============================================================================
FROM node:22.14.0-alpine@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944

WORKDIR /app

# Set environment to development
ENV NODE_ENV=development

# Copy dependency manifests
COPY package*.json ./

# Install dependencies with BuildKit cache mount (Fast BuildKit-cached dependency install)
# RUN --mount=type=cache,target=/root/.npm \
#     npm install

#Modern way to install using npm ci instead of npm install
RUN --mount=type=cache,target=/root/.npm \
    npm ci --prefer-offline --no-audit --no-fund

# Copy source code (used as a fallback if volumes aren't mounted)
COPY . .

# Expose your dev server port:
# - Vite: 5173
# - Next.js / CRA: 3000
# - Angular: 4200
EXPOSE 5173

# Start the dev server with HMR/live reload
CMD ["npm", "run", "dev"]
