apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-raw-secrets
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: restrict-raw-secret-creation
      match:
        any:
        - resources:
            kinds: [Secret]
      exclude:
        any:
        - resources:
            namespaces: [kube-system, kyverno, kube-node-lease, kube-public, external-secrets, external-secrets]
        # Allow Helm to store its release metadata:
        - resources:
            kinds: [Secret]
            names: ["sh.helm.release.*"]
        - subjects:
            - kind: ServiceAccount
              name: external-secrets
              namespace: external-secrets
      validate:
        message: "Direct creation of raw Secrets is prohibited. Use ExternalSecret manifests connected to a Vault or Cloud Secret Manager."
        deny:
          conditions:
            all:
              - key: "{{ request.operation }}"
                operator: Equals
                value: "CREATE"
