apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-resource-limits
spec:
  validationFailureAction: Enforce
  rules:
    - name: require-cpu-mem-requests-limits
      match:
        any:
        - resources:
            kinds: [Pod]
      exclude:
        any:
        - resources:
            namespaces: [kube-system, kyverno, kube-node-lease, kube-public]
      validate:
        message: "All containers must define CPU and Memory requests and limits."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"

    - name: enforce-guaranteed-memory-qos
      match:
        any:
        - resources:
            kinds: [Pod]
      exclude:
        any:
        - resources:
            namespaces: [kube-system, kyverno, kube-node-lease, kube-public]
      validate:
        message: "Memory limit must equal memory request for Guaranteed QoS."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].resources.requests.memory }}"
                operator: NotEquals
                value: "{{ request.object.spec.containers[].resources.limits.memory }}"
