apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: frontend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: frontend/credentials
