apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limit-range
  labels:
    app.kubernetes.io/name: my-app
spec:
  limits:
    - type: Container
      # 1. HARD CEILING: Blocks rogue containers from requesting too much
      max:
        cpu: 300m
        memory: 256Mi

      # 2. HARD FLOOR: Prevents un-schedulable tiny pods
      min:
        cpu: 20m
        memory: 32Mi

      # 3. AUTO-INJECTION: If a dev forgets 'limits', K8s injects these
      default:
        cpu: 150m
        memory: 128Mi

      # 4. AUTO-INJECTION: If a dev forgets 'requests', K8s injects these
      defaultRequest:
        cpu: 50m
        memory: 64Mi
