apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment # No namespace here — Kustomization sets it
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: M-treat-project
      app.kubernetes.io/component: frontend
  template:
    spec:
      containers:
        - name: frontend
