apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prod-frontend-pdb
spec:
  maxUnavailable: 1

  # ====================================================================
  # PREVENTS BROKEN PODS FROM BLOCKING NODE DRAINS / UPGRADES
  # ====================================================================
  unhealthyPodEvictionPolicy: AlwaysAllow

  selector:
    matchLabels:
      app.kubernetes.io/name: M-treat-project
      app.kubernetes.io/component: frontend
