apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.x.x
    helm:
      valuesObject:
        nodeExporter:
          enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            ruleSelectorNilUsesHelmValues: false
            ruleSelector: {}
            scrapeInterval: 60s
            evaluationInterval: 60s
            retention: 2h
            resources:
              requests:
                cpu: 50m
                memory: 150Mi
              limits:
                cpu: 200m
                memory: 350Mi
        prometheusOperator:
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 150Mi
        grafana:
          resources:
            requests:
              cpu: 20m
              memory: 80Mi
            limits:
              cpu: 100m
              memory: 180Mi
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 10m
                memory: 40Mi
              limits:
                cpu: 50m
                memory: 80Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
