apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
